config/routes.rb
Scheduler::Application.routes.draw do

  root to: "sessions#index"

  resources :bofs

  resources :lightning_talks, only: [:index, :new, :create, :show] do
    collection do
      get :now
    end
  end

  resources :sessions

  namespace :admin do
    resources :lightning_talks do
      collection do
        post :sort
      end

      member do
        post :start
        post :complete
      end
    end

    resources :bofs do
      member do
        post :start
        post :complete
      end
    end
  end

end

app/models/bof.rb
class Bof < Session
end

app/models/lightning_talk.rb
class LightningTalk < Session
  validates_presence_of :name
  validates_presence_of :title
end

app/models/session.rb
class Session < ActiveRecord::Base
  attr_accessible :description, :name, :title, :type

  scope :first_come, order(:created_at)
  scope :sorted,     order(:position)
  scope :incomplete, where('completed_at IS NULL')

  def end_time
    started_at + 5.minutes
  end

  def time_remaining(at=Time.zone.now)
    remain = end_time - at
    remain > 0 ? remain : 0
  end

  def started?
    started_at.present?
  end

  def completed?
    completed_at.present?
  end
end

app/controllers/admin/lightning_talks_controller.rb
class Admin::LightningTalksController < ApplicationController
  http_basic_authenticate_with :name => "rubyconf", :password => "ph0enix"
  respond_to :html, :js

  def sort
    params[:lightning_talk].each_with_index do |talk_id, position|
      LightningTalk.find(talk_id).update_attribute(:position, position)
    end

    render nothing: true
  end

  def index
    @lightning_talks = LightningTalk.first_come.incomplete
  end

  def start
    @lightning_talk = LightningTalk.find(params[:id])
    @lightning_talk.update_attribute(:started_at, Time.zone.now)
  end

  def complete
    @lightning_talk = LightningTalk.find(params[:id])
    @lightning_talk.update_attribute(:completed_at, Time.zone.now)

    @next = LightningTalk.first_come.incomplete.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bofs_controller.rb
class BofsController < ApplicationController
  # GET /bofs
  # GET /bofs.json
  def index
    @bofs = Bof.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bofs }
    end
  end

  # GET /bofs/1
  # GET /bofs/1.json
  def show
    @bof = Bof.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bof }
    end
  end

  # GET /bofs/new
  # GET /bofs/new.json
  def new
    @bof = Bof.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bof }
    end
  end

  # GET /bofs/1/edit
  def edit
    @bof = Bof.find(params[:id])
  end

  # POST /bofs
  # POST /bofs.json
  def create
    @bof = Bof.new(params[:bof])

    respond_to do |format|
      if @bof.save
        format.html { redirect_to @bof, notice: 'Bof was successfully created.' }
        format.json { render json: @bof, status: :created, location: @bof }
      else
        format.html { render action: "new" }
        format.json { render json: @bof.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bofs/1
  # PUT /bofs/1.json
  def update
    @bof = Bof.find(params[:id])

    respond_to do |format|
      if @bof.update_attributes(params[:bof])
        format.html { redirect_to @bof, notice: 'Bof was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bof.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bofs/1
  # DELETE /bofs/1.json
  def destroy
    @bof = Bof.find(params[:id])
    @bof.destroy

    respond_to do |format|
      format.html { redirect_to bofs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/lightning_talks_controller.rb
class LightningTalksController < ApplicationController

  def now
    @lightning_talks = LightningTalk.sorted.incomplete
  end

  # GET /lightning_talks
  # GET /lightning_talks.json
  def index
    @lightning_talks = LightningTalk.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lightning_talks }
    end
  end

  # GET /lightning_talks/1
  # GET /lightning_talks/1.json
  def show
    @lightning_talk = LightningTalk.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lightning_talk }
    end
  end

  # GET /lightning_talks/new
  # GET /lightning_talks/new.json
  def new
    @lightning_talk = LightningTalk.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lightning_talk }
    end
  end

  # GET /lightning_talks/1/edit
  def edit
    @lightning_talk = LightningTalk.find(params[:id])
  end

  # POST /lightning_talks
  # POST /lightning_talks.json
  def create
    @lightning_talk = LightningTalk.new(params[:lightning_talk])

    respond_to do |format|
      if @lightning_talk.save
        format.html { redirect_to @lightning_talk, notice: 'Lightning talk was successfully created.' }
        format.json { render json: @lightning_talk, status: :created, location: @lightning_talk }
      else
        format.html { render action: "new" }
        format.json { render json: @lightning_talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lightning_talks/1
  # PUT /lightning_talks/1.json
  def update
    @lightning_talk = LightningTalk.find(params[:id])

    respond_to do |format|
      if @lightning_talk.update_attributes(params[:lightning_talk])
        format.html { redirect_to @lightning_talk, notice: 'Lightning talk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lightning_talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lightning_talks/1
  # DELETE /lightning_talks/1.json
  def destroy
    @lightning_talk = LightningTalk.find(params[:id])
    @lightning_talk.destroy

    respond_to do |format|
      format.html { redirect_to lightning_talks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # GET /sessions
  # GET /sessions.json
  def index
    @lightning_talks = LightningTalk.all
    @bofs = Bof.all

    respond_to do |format|
      format.html
    end
  end

  # GET /sessions/1
  # GET /sessions/1.json
  def show
    @session = Session.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @session }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bofs_helper.rb
module BofsHelper
end

app/helpers/lightning_talks_helper.rb
module LightningTalksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/lightning_talks/_actions.html.erb
<%- if lightning_talk.started? -%>
  <%= link_to "end", [:complete, :admin, lightning_talk], :class => 'btn btn-large', data: { remote: true, method: :post } %>
<%- else -%>
  <%= link_to "start", [:start, :admin, lightning_talk], :class => 'btn btn-large', data: { remote: true, method: :post } %>
<%- end -%>

app/views/admin/lightning_talks/complete.js.erb
$('#<%= dom_id @lightning_talk %>').remove();
<%- if @next -%>
$('#<%= dom_id @next %> .actions').html('<%=
  escape_javascript render :partial => 'actions',
    locals: { lightning_talk: @next }
%>');
<%- end -%>

app/views/admin/lightning_talks/index.html.erb
<ul id="lightning_talks" class="sessions">
  <%- @lightning_talks.each_with_index do |lightning_talk, index| -%>
    <li id="<%= dom_id(lightning_talk) %>" class="session session-<%= index %>">
      <div class="actions">
      <%- if index.zero? -%>
        <%= render :partial => 'actions', :locals => { :lightning_talk => lightning_talk } %>
      <%- end -%>
      </div>
      <div class="title"><%= lightning_talk.title %></div>
      <div class="name"><%= lightning_talk.name %></div>
      <div class="description"><%= lightning_talk.description %></div>
    </li>
  <%- end -%>
</ul>

<script type="text/javascript">
  $(function() {
    $('#lightning_talks').sortable({
      axis: 'y',
      items: 'li',
      update: function() {
        $.post('/admin/lightning_talks/sort', $(this).sortable('serialize'), function() {
          $('#lightning_talks').effect('highlight');
          window.location.reload();
        })
      }
    });
  });
</script>

app/views/admin/lightning_talks/start.js.erb
$('#<%= dom_id @lightning_talk %> .actions').html('<%=
  escape_javascript render :partial => 'actions',
    locals: { lightning_talk: @lightning_talk }
%>');

app/views/bofs/_form.html.erb
<%= form_for(@bof) do |f| %>
  <% if @bof.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bof.errors.count, "error") %> prohibited this bof from being saved:</h2>

      <ul>
      <% @bof.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <%= f.label :name, "Speaker Name" %><br />
      <%= f.text_field :name %>
    </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bofs/edit.html.erb
<h1>Editing bof</h1>

<%= render 'form' %>

<%= link_to 'Show', @bof %> |
<%= link_to 'Back', bofs_path %>

app/views/bofs/index.html.erb
<h1>Listing Birds of a Feather</h1>

<table class="table-striped table">
  <tr>
    <th>#</th>
    <th>Speaker Name</th>
    <th>Title</th>
    <th>Description</th>
  </tr>

<% @bofs.each_with_index do |bof, idx| %>
  <tr>
    <td><%= idx.next %></td>
    <td><%= bof.title %></td>
    <td><%= bof.description %></td>
    <td><%= bof.name %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bof', new_bof_path %>

app/views/bofs/new.html.erb
<h1>New Birds of a Feather</h1>

<%= render 'form' %>

<%= link_to 'Birds of a Feathers', bofs_path %>
<%= link_to 'All Sessions', sessions_path %>

app/views/bofs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @bof.title %>
</p>

<p>
  <b>Description:</b>
  <%= @bof.description %>
</p>

<p>
  <b>Type:</b>
  <%= @bof.type %>
</p>

<p>
  <b>Name:</b>
  <%= @bof.name %>
</p>


<%= link_to 'Edit', edit_bof_path(@bof) %> |
<%= link_to 'Back', bofs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scheduler</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery-1.8.0.min" %>
  <%= javascript_include_tag "jquery-ui-1.9.1.custom.min" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="<%= root_path %>">RubyConf 2012</a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><a href="<%= lightning_talks_path %>">Lightning Talks</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div id="container">
<%= yield %>
</div>

</body>
</html>

app/views/lightning_talks/_form.html.erb
<%= form_for(@lightning_talk) do |f| %>
  <% if @lightning_talk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lightning_talk.errors.count, "error") %> prohibited this lightning_talk from being saved:</h2>

      <ul>
      <% @lightning_talk.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :name, "Speaker Name" %><br />
      <%= f.text_field :name %>
    </div>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-large btn-primary"%>
  </div>
<% end %>

app/views/lightning_talks/edit.html.erb
<h1>Editing lightning_talk</h1>

<%= render 'form' %>

<%= link_to 'Show', @lightning_talk %> |
<%= link_to 'Back', lightning_talks_path %>

app/views/lightning_talks/index.html.erb
<h1>Listing Lightning Talks</h1>

<table class="table-striped table">
  <tr>
    <th>#</th>
    <th>Speaker Name</th>
    <th>Title</th>
    <th>Description</th>
  </tr>

<% @lightning_talks.each_with_index do |lightning_talk, idx| %>
  <tr>
    <td><%= idx.next %></td>
    <td><%= lightning_talk.name %></td>
    <td><%= lightning_talk.title %></td>
    <td><%= lightning_talk.description %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lightning talk', new_lightning_talk_path, class: "btn btn-large"%>

app/views/lightning_talks/new.html.erb
<h1>New Lightning Talk</h1>

<%= render 'form' %>

<%= link_to 'Lightning Talks', lightning_talks_path %>
<%= link_to 'All Sessions', sessions_path %>

app/views/lightning_talks/now.html.erb
<div class="sessions">
<%- if now = @lightning_talks.first -%>
  <%- if now.started? && ! now.completed? -%>
    <script type="text/javascript">
      window.endTime = <%= now.end_time.to_f %>;
      window.startedFade = false;
      window.timer = null;

      function displayTime() {
        var remaining, minutes, seconds;

        remaining = endTime - (new Date().getTime() / 1000);
        minutes = parseInt(remaining / 60);
        seconds = parseInt(remaining % 60);

        if (minutes < 1 && seconds < 1) {
          minutes = 0;
          seconds = 0;
          window.clearInterval(timer);
          $('#sit-down').show();
        }

        minutes = minutes.toString();
        seconds = seconds.toString();

        if (seconds.length < 2) {
          seconds = "0" + seconds;
        }

        $('.now .timer').html(minutes + ':' + seconds);

        if (! startedFade && minutes < 1 && seconds < 30) {
          startedFade = true;
          $('body').addClass('warning');
        }

      }

      window.timer = setInterval(displayTime, 1000);

      function checkComplete() {
        $.get("/lightning_talks/<%= now.id %>.json", function(data) {
            if (data.completed_at != null) {
              window.location.reload();
            }
        });
      }

      window.timer = setInterval(checkComplete, 5000);
    </script>
  <%- end -%>
  <%- if ! now.started? -%>
    <script type="text/javascript">
      function checkStart() {
        $.get("/lightning_talks/<%= now.id %>.json", function(data) {
            if (data.started_at != null) {
              window.location.reload();
            }
        });
      }

      window.timer = setInterval(checkStart, 2000);
    </script>
  <%- end -%>
  <div class="now">
    <div class="timer"></div>
    <div class="title"><%= now.title %></div>
    <div class="name"><%= now.name %></div>
  </div>
<%- end -%>

<%- if now = @lightning_talks.second -%>
  <div class="on-deck">
    On deck:
    <div class="title"><%= now.title %></div>
    <div class="name"><%= now.name %></div>
  </div>
<%- end -%>
</div>

<div id="sit-down" style="display:none">
  .-.          <br/>
  (0.0)        <br/>
'=.|m|.='      <br/>
.='`"``=.      <br/>

<br/>
<br/>
<br/>
sit down
</div>

app/views/lightning_talks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @lightning_talk.title %>
</p>

<p>
  <b>Description:</b>
  <%= @lightning_talk.description %>
</p>

<p>
  <b>Type:</b>
  <%= @lightning_talk.type %>
</p>

<p>
  <b>Name:</b>
  <%= @lightning_talk.name %>
</p>


<%= link_to 'Back', lightning_talks_path %>